---
title: "Homework I"
author: "Cagri Gokpunar"
date: "10/29/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
```

```{r}
maindf <- read.csv("Revenue_Chart_Full_Data_data.csv")
df <- read.csv("Revenue_Chart_Full_Data_data.csv")
```

```{r}
df %<>% select("Year..copy.","Format","Value..Actual.")
```


```{r}
df %<>%  rename(Year= "Year..copy.", Value = "Value..Actual.")
```


```{r}
dfYear <- filter(df, Year > 2017 )
```
```{r}
dfYear %<>% arrange(Year)
```


```{r}
dfYear2018  <- filter(dfYear, Year==2018)
```
```{r}
sumdfYear2018 <- sum(dfYear2018$Value) 
dfYear2018
```
```{r}
dfYear2019  <- filter(dfYear, Year==2019)
```
```{r}
sumdfYear2019 <- sum(dfYear2019$Value)
dfYear2019
```
```{r}
dfYear2020  <- filter(dfYear, Year==2020)
```
```{r}
sumdfYear2020 <- sum(dfYear2020$Value) 
dfYear2020
```
```{r}
sumdfYear2018
sumdfYear2019
sumdfYear2020
```
```{r}
streaming <- c("Paid Subscription",
"On-Demand Streaming (Ad-Supported)", "Other Ad-Supported Streaming", "SoundExchange Distributions",
"Limited Tier Paid Subscription")
dfYear2020streaming <- filter(dfYear2020, Format %in% streaming)
dfYear2020streaming
```
```{r}
sumdfYear2020streaming <- sum(dfYear2020streaming$Value)
sumdfYear2020streaming
```
```{r}
synchronization <- c("Synchronization")
physical <- c("CD","LP/EP")
digitalDownloads <- c("Download Album", "Download Single")
```
```{r}
dfYear2020synchronization <- filter(dfYear2020, Format %in% synchronization)
dfYear2020physical <- filter(dfYear2020, Format %in% physical)
dfYear2020digitalDownloads <- filter(dfYear2020, Format %in% digitalDownloads)
```
```{r}
sumdfYear2020synchronization <- sum(dfYear2020synchronization$Value)
sumdfYear2020physical <- sum(dfYear2020physical$Value)
sumdfYear2020digitalDownloads <- sum(dfYear2020digitalDownloads$Value)
sumdfYear2020synchronization
sumdfYear2020physical
sumdfYear2020digitalDownloads
```
```{r}
sumdfYear2020other=sumdfYear2020-(sumdfYear2020streaming+sumdfYear2020synchronization+sumdfYear2020physical+sumdfYear2020digitalDownloads)
sumdfYear2020other
```
```{r}
 round((sumdfYear2020streaming/sumdfYear2020)*100, 2)
```
```{r}
round((sumdfYear2020synchronization/sumdfYear2020)*100, 2)
```
```{r}
round((sumdfYear2020physical/sumdfYear2020)*100, 2)
```
```{r}
round((sumdfYear2020digitalDownloads/sumdfYear2020)*100, 2)
```
```{r}
SoundExchangeDistributions <-c("SoundExchange Distributions")
OtherAdSupportedStreaming <-c("Other Ad-Supported Streaming")
dfSoundExchangeDistributions <- filter(dfYear, Format %in% SoundExchangeDistributions)
dfOtherAdSupportedStreaming <- filter(dfYear, Format %in% OtherAdSupportedStreaming)
```
```{r}
graphData<-rbind(dfSoundExchangeDistributions,dfOtherAdSupportedStreaming)
```

```{r}
ggplot(graphData, aes(fill=Format, y=Value, x=Year)) + 
    geom_bar(position="stack", stat="identity")
```